name: Build TRON GPU Miner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CUDA
      uses: Jimver/cuda-toolkit@v0.2.14
      with:
        cuda: '12.2.0'

    - name: Build with NVCC
      run: |
        mkdir build
        cd build
        nvcc ../tron/main.cu ../tron/tron.cpp ../tron/base58.c ../tron/keccak.c -o tron_gpu.exe
    
    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: tron_gpu_exe
        path: build/tron_gpu.exe
