name: Build Tron GPU Vanity Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install vcpkg dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install openssl:x64-windows

      - name: Configure (CMake)
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: tron_gpu_exe
          path: build/Release/tron_gpu.exe
