name: Build Tron GPU Vanity Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 强制走网络下载，禁用本地缓存
      - name: Install CUDA Toolkit 12.2 (no cache)
        uses: Jimver/cuda-toolkit@v0.2.14
        with:
          cuda: '12.2.0'
          method: 'network'
          use-local-cache: false

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install vcpkg + OpenSSL
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install openssl:x64-windows

      - name: Configure (CMake)
        run: >
          cmake -B build -S .
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake
          -A x64
          -DCMAKE_CUDA_ARCHITECTURES=89

      - name: Build (Release)
        run: cmake --build build --config Release

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: tron_gpu_exe
          path: build/Release/tron_gpu.exe
